name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: self-hosted

    steps:
      - name: Prenos kode
        uses: actions/checkout@v4
        
      -name: test
      run: echo "zdravo"
